### ISSUE TITLE
empl - account details

### ISSUE THREAD

**Issue by dagnyosk** [group37bookcave/BookCave#32]

**Comment by birgittab** [comment]
![image](https://user-images.githubusercontent.com/31894516/39677204-7a3b75ec-5166-11e8-9369-3d430c46c32c.png)

**Comment by birgittab** [comment]
![image](https://user-images.githubusercontent.com/31894516/39677333-a421abd6-5168-11e8-919c-adf73de5ef46.png)

**Comment by dagnyosk** [comment]
Became a B rated requirement!
